### ISSUE TITLE
Remove relative paths

### ISSUE THREAD

**Issue by szepeviktor** [conedevelopment/root#101]
### Describe the solution you'd like

Would you welcome removing all `../` from Root?
click: https://sourcegraph.com/search?q=context:global+repo:conedevelopment/root+..+NOT+...&patternType=standard

### Why do you think this feature is something we should consider for Root?

Hard to read for humans.

### Additional context

- for PHP: `dirname(__DIR__, $number)`
- for Vite: `resolve.alias` https://vitejs.dev/config/shared-options.html#resolve-alias

**Comment by szepeviktor** [comment]
```diff
- import Table from './../../Components/Table/Table.vue';
+ import Table from '@/Components/Table/Table.vue';
```

**Comment by iamgergo** [comment]
The thing is, if they publish the Root assets, and compile them from the project itself `@` symbol could cause issues, since it can be defined in the project already with a different path. While the relative paths remain the same.
