### ISSUE TITLE
Missing JSON field

### ISSUE THREAD

**Issue by szepeviktor** [conedevelopment/root#158]
Referenced in src/Form/Fields/Meta.php
https://github.com/conedevelopment/root/blob/f739845ab24ecaafcc19a9b18c1a875b597db0a5/src/Form/Fields/Meta.php#L120-L123

Was https://github.com/conedevelopment/root/blob/7a2ec959f2f2a8d024a7b3d4169a7b472c65f765/src/Form/Fields/Json.php

**Comment by iamgergo** [comment]
Fixed, thanks.
